// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKC3d3Vii12jiYqF5fl1H56Llu3V-4X-M',
    appId: '1:1038524326865:web:3254f1b6234a4859b2f6f0',
    messagingSenderId: '1038524326865',
    projectId: 'onairflutter',
    authDomain: 'onairflutter.firebaseapp.com',
    storageBucket: 'onairflutter.appspot.com',
    measurementId: 'G-G77CJWQD2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC073oTG6wZnPUFgVuoAe3Px6hgqyZlMPk',
    appId: '1:1038524326865:android:fe2b5a515ced2177b2f6f0',
    messagingSenderId: '1038524326865',
    projectId: 'onairflutter',
    storageBucket: 'onairflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSIIicYpt8bFJRiydKpFJ2UCoUlozhu9I',
    appId: '1:1038524326865:ios:3520fbeadef7565cb2f6f0',
    messagingSenderId: '1038524326865',
    projectId: 'onairflutter',
    storageBucket: 'onairflutter.appspot.com',
    iosClientId: '1038524326865-0ss7j0d1mntj444qvts0a9a3n4pkloc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.onairFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSIIicYpt8bFJRiydKpFJ2UCoUlozhu9I',
    appId: '1:1038524326865:ios:3520fbeadef7565cb2f6f0',
    messagingSenderId: '1038524326865',
    projectId: 'onairflutter',
    storageBucket: 'onairflutter.appspot.com',
    iosClientId: '1038524326865-0ss7j0d1mntj444qvts0a9a3n4pkloc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.onairFlutter',
  );
}
